"""add original_filename to csv_uploads

Revision ID: 22fbdfeb8489
Revises: 44fe4a84fd60
Create Date: 2026-07-09 15:03:23.394709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22fbdfeb8489'
down_revision: Union[str, Sequence[str], None] = '44fe4a84fd60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csv_uploads', sa.Column('original_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csv_uploads', 'original_filename')
    # ### end Alembic commands ###
