"""add csv_uploads table

Revision ID: 4399d0a3f196
Revises: a1eed64414ba
Create Date: 2026-06-30 00:06:27.086419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4399d0a3f196'
down_revision: Union[str, Sequence[str], None] = 'a1eed64414ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nbfc_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('minio_object_key', sa.String(length=500), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('ingested_count', sa.Integer(), nullable=True),
    sa.Column('skipped_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'complete', 'failed', name='uploadstatus'), nullable=False),
    sa.Column('error_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nbfc_id'], ['nbfcs.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('csv_uploads')
    # ### end Alembic commands ###
