"""add interaction_logs table

Revision ID: 44fe4a84fd60
Revises: 4399d0a3f196
Create Date: 2026-07-03 19:48:15.076196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44fe4a84fd60'
down_revision: Union[str, Sequence[str], None] = '4399d0a3f196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('borrower_id', sa.UUID(), nullable=False),
    sa.Column('nbfc_id', sa.UUID(), nullable=True),
    sa.Column('logged_by', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.Enum('telecall', 'field_visit', 'whatsapp_outbound', 'system', name='interactiontype'), nullable=False),
    sa.Column('outcome', sa.Enum('promise_to_pay', 'not_reachable', 'dispute', 'already_paid', 'payment_collected', 'not_found', 'refused', 'message_sent', 'message_delivered', 'message_read', name='interactionoutcome'), nullable=False),
    sa.Column('ptp_date', sa.Date(), nullable=True),
    sa.Column('ptp_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ptp_broken', sa.Boolean(), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.Column('is_offline_log', sa.Boolean(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('server_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nbfc_id'], ['nbfcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interaction_logs')
    # ### end Alembic commands ###
