"""add nbfcs and borrowers tables

Revision ID: a1eed64414ba
Revises: 90d61c173fb8
Create Date: 2026-06-29 11:35:02.883069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1eed64414ba'
down_revision: Union[str, Sequence[str], None] = '90d61c173fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nbfcs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('whatsapp_business_account_id', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_phone_number_id', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_access_token', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('borrowers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nbfc_id', sa.UUID(), nullable=True),
    sa.Column('loan_account_number', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('preferred_language', sa.Enum('hindi', 'english', name='preferredlanguage'), nullable=True),
    sa.Column('emi_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('outstanding_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('dpd_days', sa.Integer(), nullable=True),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('last_payment_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sma_bucket', sa.Enum('SMA_0', 'SMA_1', 'SMA_2', 'NPA', name='smabucket'), nullable=True),
    sa.Column('priority_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('priority_reason', sa.String(), nullable=True),
    sa.Column('priority_action', sa.Enum('telecaller_call', 'whatsapp', 'field_visit', name='priorityaction'), server_default='telecaller_call', nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['nbfc_id'], ['nbfcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrowers')
    op.drop_table('nbfcs')
    # ### end Alembic commands ###
